services:
    rage-core:
        image: rage-core
        container_name: rage-core
        build:
            context: .
            dockerfile: ./docker/core/Dockerfile
        volumes:
            - $PWD/resources:/resources
            - $PWD/notebooks:/notebooks
        env_file:
            - .env
        networks:
            - rage

    rage-redis:
        image: redis:8.0.2
        container_name: rage-redis
        volumes:
            - $PWD/resources/cache/redis:/data
        command:
            [
                "redis-server",
                "--appendonly",
                "no",
                "--maxmemory",
                "128mb",
                "--maxmemory-policy",
                "allkeys-lru",
            ]
        deploy:
            resources:
                limits:
                    memory: 192M
        restart: unless-stopped
        networks:
            - rage

    rage-qdrant:
        image: qdrant/qdrant:v1.14.1
        container_name: rage-qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        volumes:
            - ./resources/db/qdrant:/qdrant/storage
        restart: unless-stopped
        networks:
            - rage

networks:
    rage:
        name: rage
        driver: bridge
