services:
    rage-devcontainer:
        image: rage-devcontainer
        container_name: rage-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        env_file:
            - ../.env
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - rage

networks:
    rage:
        name: rage
        driver: bridge
