name: Publish (GitHub PyPI)

on:
    push:
        tags: ["v*"]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build distributions
              run: |
                  python -m build
                  ls -lh dist

            - name: Publish to GitHub Packages (PyPI)
              env:
                  OWNER: ${{ github.repository_owner }}
                  TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  USERNAME: ${{ github.actor }}
              run: |
                  python -m twine upload \
                    --skip-existing \
                    --username "$USERNAME" \
                    --password "$TOKEN" \
                    --repository-url "https://upload.pypi.pkg.github.com/${OWNER}/" \
                    dist/*
