name: Publish (GitHub PyPI)

on:
    push:
        tags: ["v*"]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install build tooling
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine

            - name: Build distributions
              run: |
                  python -m build
                  ls -lh dist

            - name: Publish to GitHub Packages (PyPI)
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  OWNER: ${{ github.repository_owner }}
              run: |
                  # Twine token auth: username can be __token__
                  # Try org endpoint first, fall back to user endpoint.
                  python -m twine upload \
                    --username __token__ \
                    --password "$GITHUB_TOKEN" \
                    --repository-url "https://api.github.com/orgs/${OWNER}/packages/pypi/upload" \
                    dist/* \
                  || python -m twine upload \
                    --username __token__ \
                    --password "$GITHUB_TOKEN" \
                    --repository-url "https://api.github.com/users/${OWNER}/packages/pypi/upload" \
                    dist/*
